### ISSUE TITLE
Several functions: Error in if ((nrow(ims) == 0) | (nrow(users) == 0)) 

### ISSUE THREAD

**Issue by herrseverin** [mrkaye97/slackr#120] opened 2020-12-21 10:30 UTC
I always get the same error for several functions. `text_slackr` is working fine. 
`slackr` or `slackr_msg` throws

`Fehler in if ((nrow(ims) == 0) | (nrow(users) == 0)) { : 
  Argument hat L"ange 0`

that translates:
`Error in if ((nrow(ims) == 0) | (nrow(users) == 0)) { : Argument has length 0`

And `slackr_setup` throw (i deleted the tokens):
`{
  "SLACK_CHANNEL": ["#al."],
  "SLACK_USERNAME": ["py..."],
  "SLACK_ICON_EMOJI": [""],
  "SLACK_INCOMING_URL_PREFIX": ["https://hooks.slack.com/s..."],
  "SLACK_BOT_USER_OAUTH_TOKEN": ["xoxb-..."]
} 
Fehler in if ((nrow(ims) == 0) | (nrow(users) == 0)) { : 
  Argument hat L"ange 0`

At the same time
slackr_bot("iris info", head(iris), str(iris)) throws
`Warnmeldung:
In slackr_bot("iris info", head(iris), str(iris)) : Bad Request (HTTP 400).`
while `slackr_bot("iris info")` is working. 

My bot scopes.
<img width="659" alt="Bildschirmfoto 2020-12-21 um 10 02 12" src="https://user-images.githubusercontent.com/1457441/102767149-6c312600-437f-11eb-9812-3233b8d53ff4.png">

`sessionInfo`:

`R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin19.6.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /usr/local/Cellar/r/4.0.3/lib/R/lib/libRlapack.dylib

locale:
[1] de_DE.UTF-8/de_DE.UTF-8/de_DE.UTF-8/C/de_DE.UTF-8/de_DE.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] slackr_2.0.1

loaded via a namespace (and not attached):
 [1] compiler_4.0.3    pillar_1.4.7      prettyunits_1.1.1 remotes_2.2.0     tools_4.0.3      
 [6] testthat_3.0.1    digest_0.6.27     pkgbuild_1.2.0    pkgload_1.1.0     jsonlite_1.7.2   
[11] gtable_0.3.0      memoise_1.1.0     lifecycle_0.2.0   tibble_3.0.4      pkgconfig_2.0.3  
[16] rlang_0.4.9       cli_2.2.0         rstudioapi_0.13   curl_4.3          httr_1.4.2       
[21] withr_2.3.0       dplyr_1.0.2       desc_1.2.0        generics_0.1.0    fs_1.5.0         
[26] vctrs_0.3.6       devtools_2.3.2    grid_4.0.3        rprojroot_2.0.2   tidyselect_1.1.0 
[31] glue_1.4.2        R6_2.5.0          processx_3.4.5    fansi_0.4.1       sessioninfo_1.1.1
[36] callr_3.5.1       purrr_0.3.4       ggplot2_3.3.2     magrittr_2.0.1    scales_1.1.1     
[41] ps_1.5.0          ellipsis_0.3.1    usethis_1.6.3     assertthat_0.2.1  colorspace_2.0-0 
[46] munsell_0.5.0     crayon_1.3.4`

Thank you very much. Stay healthy and have a nice christmas!

**Comment by mrkaye97** [comment] 2020-12-21 14:55
Thanks for the note! I'll look into this for a few. Off the top of my head, it sounds like a scopes / permissions / token issue. As mentioned in #114, you can [test your Slack token here](https://api.slack.com/methods/conversations.list/test) to see if it's finding the channels in your workspace. Let me know if you try that and nothing shows up. 

Also, do you mind reproducing this error and pasting the traceback here? You can get the error with `rlang::last_error()` and the traceback with `rlang::last_trace()`. That'll help me debug.

**Comment by herrseverin** [comment] 2020-12-22 13:04
Thanks in advance for your immediate response. 

Interestingly, both `last_error` and `last_trace` did not display an error, just say "there was no error." I had a look at the `slackr` function. This uses `slackr_chtrans`, which in turn uses `slackr_census`, which in turn uses `slackr_channels`. Of course you know all this. 

`slackr_channels` does not work, because the API returns the response that the scope is not sufficient. `"IM:READ"` is missing. That again is not in the required scopes on the github page of slackr. Adding this scope makes `Fehler in if ((nrow(ims) == 0) | (nrow(users) == 0)) { : Argument hat L"ange 0` disappear. 

slackr_bot(str(iris)) still throws a `In slackr_bot(str(iris)) : Bad Request (HTTP 400)`.

**Comment by mrkaye97** [comment] 2020-12-22 15:28
Thanks for digging around. I can add a more informative error for when that happens + add `im:read` to the necessary scopes in the readme. Thanks for pointing that out. I'm not 100% sure about the `slack_bot()` error. It might be due to the webhook? Does `slackr(str(iris))` work?

**Comment by mrkaye97** [comment] 2021-01-17 15:34
This should be fixed in `slackr 2.0.2+`

**Closed as completed by mrkaye97** 2021-01-17 15:34 UTC
Labels: bug

**Comment by herrseverin** [comment] 2021-01-17 20:41
Many thanks. Sorry for my late reply. Corona and its consequences keep swirling everything around.
