### ISSUE TITLE
ggslackr error

### ISSUE THREAD

**Issue by marolopnaiba** [mrkaye97/slackr#140] opened 2021-02-04 06:43 UTC
Hi, I've recently trying to post a ggplot chart using ggslackr with below code:
```
slackr::ggslackr(
  plot,
  channels = Sys.getenv("SLACK_CHANNEL"),
  bot_user_oauth_token = Sys.getenv("SLACK_BOT_USER_OAUTH_TOKEN"),
  file = "ggplot"
)
```

However, it returns the below error code:
![image](https://user-images.githubusercontent.com/48007494/106854942-c0555700-66ee-11eb-8f80-3dd221c4e841.png)
Is there something wrong with what I am doing? or it is just the scope issues?

Below are the slack_setup( ) I've used:
```
slackr_setup(channel="#test_slack_alert_mn",
            icon_emoji = "",
            incoming_webhook_url=whurl,
            bot_user_oauth_token=apitk,
            echo = FALSE,
            cache_dir = "")
``` 
Thank you in advance

**Comment by marolopnaiba** [comment] 2021-02-04 07:20
![image](https://user-images.githubusercontent.com/48007494/106858660-96069800-66f4-11eb-8728-e5a79b9b67ae.png)

the error message showed up when I run `modchan = slackr_chtrans(channels)`

**Comment by mrkaye97** [comment] 2021-02-04 13:44
This seems like `cachem` issue. Can you print the traceback for this error?  I can't reproduce it.

**Comment by marolopnaiba** [comment] 2021-02-18 02:32
Hi, sorry to get back this long
I found the same error code for `slackr_upload`, `ggslackr`, `slackr_msg` .
Same error message 
```
Error in `_cache`$digest(c(body(`_f`), args, lapply(`_additional`, function(x) eval(x[[2L]],  : 
  attempt to apply non-function
```

Below is the script used, 
```
#plot
data=head(mtcars, 30)
plot = ggplot(data, aes(x=wt, y=mpg)) +
  geom_point() + # Show dots
  geom_text(
    label=rownames(data), 
    nudge_x = 0.25, nudge_y = 0.25, 
    check_overlap = T
  )
plot

slackr::ggslackr(plot = plot, channels = Sys.getenv("SLACK_CHANNEL"), bot_user_oauth_token = Sys.getenv("SLACK_BOT_USER_OAUTH_TOKEN"), file = "ggplot")
```

Trying to get the last traceback, however, no error was recorded.
![image](https://user-images.githubusercontent.com/48007494/108296265-cad21f00-71cb-11eb-8293-751ff9cb8708.png)

**Comment by mrkaye97** [comment] 2021-02-18 03:03
Okay, AFAICT this is an issue with `cachem` and not with `slackr`. If you can, try to make a `reprex` of the issue. FYI, the only thing I'm relying on `cachem` for in `slackr` is to cache the channels in your workspace (by memoizing `slackr_census()`, so my guess is a `reprex` that simply tests if memoization works on your machine might give you this error too. Feel free to report back if you need help with a `reprex`. You should be able to do something like this:

```r
reprex::reprex({
  library(memoise)
  square <- function(x) {
    x * x
  }

  memo_square <- memoise(square)

  square(2)
  memo_square(2)
})
```

I presume that if that `reprex` works, then it might have something to do with caching to the disk, but I'd try something like that first to see if you can reproduce the error

**Comment by katrinabrock** [comment] 2021-02-26 02:11
I hit this issue as well. It is definitely related to cachem. As a workaround, I rolled back to this commit https://github.com/mrkaye97/slackr/commit/9a68e3acd8812c38a82adb178bcdbbbe4678f7a1 before the introduction of cachem.

**Comment by mrkaye97** [comment] 2021-02-26 02:52
@katrinabrock Thanks for the input! I'm actually a little surprised that commit worked, as it's from after `cachem` was introduced. Are you sure that's the right one? Hopefully a future version of `cachem` will fix this issue. Can you reproduce it in a `reprex` outside of `slackr`?

**Comment by katrinabrock** [comment] 2021-02-27 00:00
@mrkaye97 I'm not too familiar with reprex, but here's some code

```{r}
install.packages('cachem', repo = "https://mran.microsoft.com/snapshot/2021-02-26/")

square <- function(x) {
  x * x
}

memo_square_default <- memoise::memoise(square) 
memo_square_cache_mem <- memoise::memoise(square, cache = cachem::cache_mem()) 
memo_square_cach_disk <- memoise::memoise(square, cache = cachem::cache_disk('/tmp')) 

square(2)
memo_square_default(2)
memo_square_cache_mem(2)
memo_square_cach_disk(2)
```

Result:
```
> square(2)
[1] 4
> memo_square_default(2)
[1] 4
> memo_square_cache_mem(2)
Error in memo_square_cache_mem(2) : attempt to apply non-function
No traceback available 
> memo_square_cach_disk(2)
Error in memo_square_cach_disk(2) : attempt to apply non-function
1: memo_square_cache_mem(2)
```

This is on R `4.0.3` btw. I need to do some checking on version of memoise. I suspect there may be a mixmatch causing the problem.

----

I think you also have a bug on this line: https://github.com/mrkaye97/slackr/blob/master/R/slackr_utils.R#L74

If `SLACK_CACHE_DIR` environment var is set, package will fail to load because `cache_dir` is not assigned. LMK if you would like me to open another issue or just a PR for this.

**Comment by mrkaye97** [comment] 2021-02-27 00:21
@katrinabrock Interesting, thanks for the code! 

This actually runs on my machine, but I also spun up a Docker container and it won't run on there (same error as you). I'm running this on `memoise 1.1.0` and `cachem 1.0.4` in the Docker container, and it breaks. Locally I'm on `memoise 2.0.0` and `cachem 1.0.4` and it runs fine. It might be worth updating `memoise` to see if that fixes the issue. If it does, I'll add a note to the README about this and bump the dependency version. 

Nice catch on that bug! It'd be awesome if you could PR a fix. Thanks a bunch!

**Comment by katrinabrock** [comment] 2021-02-27 00:24
>It might be worth updating memoise.

I think that's exactly the issue.

>It'd be awesome if you could PR a fix.

ok, will do

**Comment by mrkaye97** [comment] 2021-02-27 00:55
Closing in the hopes that #146 fixes this bug. Will reopen if it doesn't

**Closed as completed by mrkaye97** 2021-02-27 00:55 UTC
